
spring :
  application:
    name: message-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/message-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

# config private key
jwt :
  secret : SK40CSI2PC-D#?4klj50fdl3kd3ldư;l3ke

server:
  port: 8080